apiVersion: v1
kind: Pod
metadata:
  name: single-pod
spec:
  containers:
    - name: server
      image: fpjack/sample-app
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP